# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/UART_USB/UART_USB.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UART_USB || ORIG_REF_NAME==UART_USB} -quiet] -quiet

# IP: bd/UART_USB/ip/UART_USB_processing_system7_0_0/UART_USB_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UART_USB_processing_system7_0_0 || ORIG_REF_NAME==UART_USB_processing_system7_0_0} -quiet] -quiet

# IP: bd/UART_USB/ip/UART_USB_axi_gpio_0_0/UART_USB_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UART_USB_axi_gpio_0_0 || ORIG_REF_NAME==UART_USB_axi_gpio_0_0} -quiet] -quiet

# IP: bd/UART_USB/ip/UART_USB_axi_gpio_1_0/UART_USB_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UART_USB_axi_gpio_1_0 || ORIG_REF_NAME==UART_USB_axi_gpio_1_0} -quiet] -quiet

# IP: bd/UART_USB/ip/UART_USB_xbar_0/UART_USB_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UART_USB_xbar_0 || ORIG_REF_NAME==UART_USB_xbar_0} -quiet] -quiet

# IP: bd/UART_USB/ip/UART_USB_auto_pc_0/UART_USB_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UART_USB_auto_pc_0 || ORIG_REF_NAME==UART_USB_auto_pc_0} -quiet] -quiet

# IP: bd/UART_USB/ip/UART_USB_ps7_0_axi_periph_0/UART_USB_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UART_USB_ps7_0_axi_periph_0 || ORIG_REF_NAME==UART_USB_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/UART_USB/ip/UART_USB_rst_ps7_0_100M_0/UART_USB_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UART_USB_rst_ps7_0_100M_0 || ORIG_REF_NAME==UART_USB_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/UART_USB/UART_USB_ooc.xdc
