#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Sep 22 15:40:38 EDT 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 215fd465833742eca04e7dc39dd430d6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot test_file_behav xil_defaultlib.test_file -log elaborate.log"
xelab -wto 215fd465833742eca04e7dc39dd430d6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot test_file_behav xil_defaultlib.test_file -log elaborate.log

