# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/UART/UART.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UART || ORIG_REF_NAME==UART} -quiet] -quiet

# IP: bd/UART/ip/UART_processing_system7_0_0/UART_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UART_processing_system7_0_0 || ORIG_REF_NAME==UART_processing_system7_0_0} -quiet] -quiet

# XDC: bd/UART/UART_ooc.xdc
