set_property SRC_FILE_INFO {cfile:{/afs/ee.cooper.edu/user/d/david.yang/Hardware Design/Week3_VHDL/Week3_VHDL.srcs/constrs_1/new/Week3_VHDL_cnstr.xdc} rfile:../../../Week3_VHDL.srcs/constrs_1/new/Week3_VHDL_cnstr.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports A]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports B]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports C]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W22 [get_ports D]
