webtalk_init -webtalk_dir /afs/ee.cooper.edu/user/d/david.yang/Hardware Design/Pipeline_MIPS/MIPS.sim/sim_1/impl/timing/xsim/xsim.dir/tb_time_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Nov  4 02:58:47 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "76953919-7677-4a60-a845-304a55f46bf4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c9be953bc0de46dfa7f579575bab88e9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux 10 (buster)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4302.616 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "825 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.10_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "127288_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3312589236 -regid "" -xml /afs/ee.cooper.edu/user/d/david.yang/Hardware Design/Pipeline_MIPS/MIPS.sim/sim_1/impl/timing/xsim/xsim.dir/tb_time_impl/webtalk/usage_statistics_ext_xsim.xml -html /afs/ee.cooper.edu/user/d/david.yang/Hardware Design/Pipeline_MIPS/MIPS.sim/sim_1/impl/timing/xsim/xsim.dir/tb_time_impl/webtalk/usage_statistics_ext_xsim.html -wdm /afs/ee.cooper.edu/user/d/david.yang/Hardware Design/Pipeline_MIPS/MIPS.sim/sim_1/impl/timing/xsim/xsim.dir/tb_time_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
