# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /afs/ee.cooper.edu/user/d/david.yang/UART_3/UART_3.srcs/sources_1/bd/UART/ip/UART_processing_system7_0_0/UART_processing_system7_0_0.xci
# IP: The module: 'UART_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/ee.cooper.edu/user/d/david.yang/UART_3/UART_3.srcs/sources_1/bd/UART/ip/UART_processing_system7_0_0/UART_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /afs/ee.cooper.edu/user/d/david.yang/UART_3/UART_3.srcs/sources_1/bd/UART/ip/UART_processing_system7_0_0/UART_processing_system7_0_0.xci
# IP: The module: 'UART_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/ee.cooper.edu/user/d/david.yang/UART_3/UART_3.srcs/sources_1/bd/UART/ip/UART_processing_system7_0_0/UART_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
