set_property SRC_FILE_INFO {cfile:{/afs/ee.cooper.edu/user/d/david.yang/Hardware Design/Week 4/Week4b/Week4b.srcs/constrs_1/new/Week4b_cnstr.xdc} rfile:../../../Week4b.srcs/constrs_1/new/Week4b_cnstr.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports x]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports y]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports s]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W22 [get_ports mux]
